### ISSUE TITLE
YAML may be a better choice for recipe than Config

### ISSUE THREAD

**Issue by muma378** [muma378/moose#40]
links:
* http://www.ruanyifeng.com/blog/2016/07/yaml.html
* http://pyyaml.org/wiki/PyYAMLDocumentation

_Config_
```
[common]
root = /root/path/to/
base = /root/path/	# to remove
name = 				# custom defined
tasks = task_20717,task_20718

[task_20717]
title =
root  =  
subdirs = 

[task_20718]
title = 
subdirs = 
```

_YAML_
```
root: /root/path/to
base: /root/path
tasks:
  - 
    task_id: 20717
    title: 
    subdirs: 
  -
    task_id: 20718
    subdirs: 
```
